spring.application.name: api-gateway

server.port: 8080
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
jwt.secretKey: aljfoewjfopl**/--@3klafhkkglajfjoelj#$%dslhgbsl(0^hsh

#
#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    reactor.netty.http.client: TRACE




spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2


        - id: user-service_protected
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/protected/**
          filters:
            - StripPrefix=2



        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


        - id: connections-service
          uri: lb://CONNECTIONS-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
