spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 9050

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: dryzsrjx9
  api-key: 552943222714854
  api-secret: 1dlBS-5aoD8DuitTrwswhz7_V7w